rootProject.name = 'logicforge'

include 'logic-core'
include 'circuit-model'
include 'simulation-core'
include 'logic-analyzer'
include 'component-library'
include 'component-structures'
include 'circuit-compiler'
include 'project-format'
include 'processor-lf8'
include 'lf8-tools'
include 'ui'
include 'app'
