package dev.logicforge.format;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import dev.logicforge.circuit.document.CircuitDocument;
import dev.logicforge.circuit.document.CircuitProject;
import dev.logicforge.circuit.document.ComponentInstance;
import dev.logicforge.circuit.document.PortReference;
import dev.logicforge.compiler.CircuitCompiler;
import dev.logicforge.compiler.CompilationResult;
import dev.logicforge.library.ComponentRegistry;
import dev.logicforge.logic.LogicState;
import dev.logicforge.logic.LogicVector;
import dev.logicforge.simulation.Simulation;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * The example circuits that ship with LogicForge really load, really compile and really
 * simulate. They are generated by the application's save path, so this also guards the
 * format against silent drift.
 */
class ExampleProjectsTest {

    private static final Path EXAMPLES =
            Path.of(System.getProperty("logicforge.examples", "../examples"));

    static Stream<Path> exampleFiles() throws IOException {
        try (var files = Files.list(EXAMPLES)) {
            return files.filter(file -> file.toString().endsWith("." + ProjectFormat.EXTENSION))
                    .sorted()
                    .toList()
                    .stream();
        }
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("exampleFiles")
    void everyExampleLoadsCompilesAndRuns(Path file) {
        CircuitProject project = ProjectFormat.load(file);
        CircuitDocument circuit = project.mainCircuit();

        assertFalse(circuit.components().isEmpty(), file + " is empty");
        assertFalse(circuit.connections().isEmpty(), file + " has no wires");

        CompilationResult compiled = new CircuitCompiler(ComponentRegistry.standard()).compile(circuit);
        Simulation simulation = new Simulation(compiled.circuit());

        assertTrue(simulation.isStable(), file + " does not settle");
        assertTrue(compiled.issues().stream().noneMatch(issue -> issue.isError()));
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("exampleFiles")
    void everyExampleSurvivesASaveAndLoadCycle(Path file) {
        CircuitProject original = ProjectFormat.load(file);
        CircuitProject reloaded = ProjectFormat.fromJson(ProjectFormat.toJson(original), "copy");

        assertTrue(original.mainCircuit().structurallyEquals(reloaded.mainCircuit()));
    }

    @Test
    void theHalfAdderExampleAddsCorrectly() {
        CircuitDocument circuit = ProjectFormat
                .load(EXAMPLES.resolve("Half-Adder." + ProjectFormat.EXTENSION)).mainCircuit();
        CompilationResult compiled = new CircuitCompiler(ComponentRegistry.standard()).compile(circuit);
        Simulation simulation = new Simulation(compiled.circuit());

        int switchA = compiled.componentByLabel("A").orElseThrow();
        int switchB = compiled.componentByLabel("B").orElseThrow();
        int sum = compiled.sourceMap().netOf(port(circuit, "SUM", "IN")).orElseThrow();
        int carry = compiled.sourceMap().netOf(port(circuit, "CARRY", "IN")).orElseThrow();

        for (List<LogicState> inputs : List.of(
                List.of(LogicState.ZERO, LogicState.ZERO, LogicState.ZERO, LogicState.ZERO),
                List.of(LogicState.ONE, LogicState.ZERO, LogicState.ONE, LogicState.ZERO),
                List.of(LogicState.ZERO, LogicState.ONE, LogicState.ONE, LogicState.ZERO),
                List.of(LogicState.ONE, LogicState.ONE, LogicState.ZERO, LogicState.ONE))) {
            simulation.setInput(switchA, inputs.get(0));
            simulation.setInput(switchB, inputs.get(1));
            assertEquals(LogicVector.single(inputs.get(2)), simulation.readNet(sum),
                    inputs.get(0) + " + " + inputs.get(1) + " sum");
            assertEquals(LogicVector.single(inputs.get(3)), simulation.readNet(carry),
                    inputs.get(0) + " + " + inputs.get(1) + " carry");
        }
    }

    @Test
    void theTriStateExampleShowsAllFourStates() {
        CircuitDocument circuit = ProjectFormat
                .load(EXAMPLES.resolve("Tri-State-Bus." + ProjectFormat.EXTENSION)).mainCircuit();
        CompilationResult compiled = new CircuitCompiler(ComponentRegistry.standard()).compile(circuit);
        Simulation simulation = new Simulation(compiled.circuit());

        int enableA = compiled.componentByLabel("ENABLE_A").orElseThrow();
        int enableB = compiled.componentByLabel("ENABLE_B").orElseThrow();
        int bus = compiled.sourceMap().netOf(port(circuit, "BUS", "IN")).orElseThrow();

        assertEquals(LogicVector.HIGH_IMPEDANCE, simulation.readNet(bus), "nobody drives the bus");

        simulation.setInput(enableA, LogicState.ONE);
        assertEquals(LogicVector.ZERO, simulation.readNet(bus));

        simulation.setInput(enableB, LogicState.ONE);
        assertEquals(LogicVector.UNKNOWN, simulation.readNet(bus), "two drivers disagree");
        assertTrue(simulation.hasDriverConflict(bus));

        simulation.setInput(enableA, LogicState.ZERO);
        assertEquals(LogicVector.ONE, simulation.readNet(bus));
    }

    private static PortReference port(CircuitDocument circuit, String label, String portName) {
        ComponentInstance instance = circuit.components().stream()
                .filter(component -> component.label().equals(label))
                .findFirst()
                .orElseThrow(() -> new AssertionError("No component labelled " + label));
        return new PortReference(instance.id(), portName);
    }
}
